# $Id$
#
# Macro file for "Artie.cc"
# (can be run in batch, without graphic)
#
# neutron 2 MeV; all processes
#
/random/setSeeds 364264876 673418543
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
#
# this will dump the entire list of commands:
#/control/manual /
# this will dump all processes:
#/process/list
#
/testhadr/phys/thermalScattering true
/artie/det/target_material argon_liquid
/primaryGenerator/SetEnergyRange 40 70 #in keV
/primaryGenerator/UseUserDefinedEnergy Resolution13a.root tally5

/analysis/ntuple_filename argon.root
/run/initialize
/run/printProgress 1000
/run/beamOn 100000
