# $Id$
#
# Macro file for "Hadr04.cc"
# (can be run in batch, without graphic)
#
# neutron 2 MeV; all processes
#
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
#
/testhadr/phys/thermalScattering true
#
/run/initialize
#
/process/list
#
/gun/particle neutron
/gun/energy 2 MeV
#
/analysis/setFileName Artie_vacuum_fill
/analysis/h1/set 0  100  0. 100. none	#nb colli >1eV
/analysis/h1/set 1  100  0. 100. cm	#track len >1eV
/analysis/h1/set 2  100  0. 5. us	#time of flight >1eV
/analysis/h1/set 3  100  0. 1000. none	#nb colli <1eV
/analysis/h1/set 4  100  0. 500. cm	#track len <1eV
/analysis/h1/set 5  100  0. 1000. us	#time of flight <1eV
/analysis/h1/set 6  1000  0. 100. us	#time of flight seen by the neutron detector
/analysis/h1/set 7  1000  0. 1 MeV	#step energy of the primary neutron
/analysis/h1/set 8  50  0.04 0.09 MeV	#energy of the transmitted neutron getting into the detector
/analysis/h1/set 9  50  0.04 0.09 MeV	#energy of the beam neutron 
/analysis/h2/set 0 1000  0. 1 MeV none linear 100  0. 100. us none linear #Detected TOF vs Energy 
#
/run/printProgress 200
#
/run/beamOn 100000
